server: {
  ip: 0.0.0.0,
  port: 8080,
  mode : release,
}

logger: {
  logfile: stdout,
  level: debug,
}

database: {
  dbms: postgres,
  host: postgres,
  user: drello_user,
  password: drello1234,
  name: drello_db,
  sslmode: disable
}

memcached: {
  host: memcached,
  port: 11211,
}

frontend: {
  protocol: http,
  ip: 89.208.197.150,
  port: 5757,
  public_dir: /home/timofeyrazumov/TP/front/2020_1_SIBIRSKAYA_KORONA/public,
  #relative
  avatar_dir: /img/avatar,
  default_avatar: /img/default_avatar.png
}
