// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "github.com/go-park-mail-ru/2020_1_SIBIRSKAYA_KORONA/app/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUseCase is a mock of UseCase interface
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockUseCase) Create(lbl *models.Label) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", lbl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockUseCaseMockRecorder) Create(lbl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUseCase)(nil).Create), lbl)
}

// Get mocks base method
func (m *MockUseCase) Get(bid, lid uint) (*models.Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", bid, lid)
	ret0, _ := ret[0].(*models.Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockUseCaseMockRecorder) Get(bid, lid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUseCase)(nil).Get), bid, lid)
}

// Update mocks base method
func (m *MockUseCase) Update(lbl models.Label) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", lbl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockUseCaseMockRecorder) Update(lbl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUseCase)(nil).Update), lbl)
}

// Delete mocks base method
func (m *MockUseCase) Delete(lid uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", lid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockUseCaseMockRecorder) Delete(lid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUseCase)(nil).Delete), lid)
}

// AddLabelOnTask mocks base method
func (m *MockUseCase) AddLabelOnTask(lid, tid uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLabelOnTask", lid, tid)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLabelOnTask indicates an expected call of AddLabelOnTask
func (mr *MockUseCaseMockRecorder) AddLabelOnTask(lid, tid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLabelOnTask", reflect.TypeOf((*MockUseCase)(nil).AddLabelOnTask), lid, tid)
}

// RemoveLabelFromTask mocks base method
func (m *MockUseCase) RemoveLabelFromTask(lid, tid uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLabelFromTask", lid, tid)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveLabelFromTask indicates an expected call of RemoveLabelFromTask
func (mr *MockUseCaseMockRecorder) RemoveLabelFromTask(lid, tid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLabelFromTask", reflect.TypeOf((*MockUseCase)(nil).RemoveLabelFromTask), lid, tid)
}
