// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "github.com/go-park-mail-ru/2020_1_SIBIRSKAYA_KORONA/app/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockRepository) Create(lbl *models.Label) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", lbl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockRepositoryMockRecorder) Create(lbl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), lbl)
}

// Get mocks base method
func (m *MockRepository) Get(lid uint) (*models.Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", lid)
	ret0, _ := ret[0].(*models.Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockRepositoryMockRecorder) Get(lid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), lid)
}

// Update mocks base method
func (m *MockRepository) Update(lbl models.Label) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", lbl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockRepositoryMockRecorder) Update(lbl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), lbl)
}

// Delete mocks base method
func (m *MockRepository) Delete(lid uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", lid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockRepositoryMockRecorder) Delete(lid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), lid)
}

// AddLabelOnTask mocks base method
func (m *MockRepository) AddLabelOnTask(lid, tid uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLabelOnTask", lid, tid)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLabelOnTask indicates an expected call of AddLabelOnTask
func (mr *MockRepositoryMockRecorder) AddLabelOnTask(lid, tid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLabelOnTask", reflect.TypeOf((*MockRepository)(nil).AddLabelOnTask), lid, tid)
}

// RemoveLabelFromTask mocks base method
func (m *MockRepository) RemoveLabelFromTask(lid, tid uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLabelFromTask", lid, tid)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveLabelFromTask indicates an expected call of RemoveLabelFromTask
func (mr *MockRepositoryMockRecorder) RemoveLabelFromTask(lid, tid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLabelFromTask", reflect.TypeOf((*MockRepository)(nil).RemoveLabelFromTask), lid, tid)
}
