// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserMess struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Surname              string   `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
	Nickname             string   `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Avatar               string   `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Password             []byte   `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMess) Reset()         { *m = UserMess{} }
func (m *UserMess) String() string { return proto.CompactTextString(m) }
func (*UserMess) ProtoMessage()    {}
func (*UserMess) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *UserMess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMess.Unmarshal(m, b)
}
func (m *UserMess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMess.Marshal(b, m, deterministic)
}
func (m *UserMess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMess.Merge(m, src)
}
func (m *UserMess) XXX_Size() int {
	return xxx_messageInfo_UserMess.Size(m)
}
func (m *UserMess) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMess.DiscardUnknown(m)
}

var xxx_messageInfo_UserMess proto.InternalMessageInfo

func (m *UserMess) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserMess) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserMess) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *UserMess) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserMess) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserMess) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserMess) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

type UidMess struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UidMess) Reset()         { *m = UidMess{} }
func (m *UidMess) String() string { return proto.CompactTextString(m) }
func (*UidMess) ProtoMessage()    {}
func (*UidMess) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *UidMess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UidMess.Unmarshal(m, b)
}
func (m *UidMess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UidMess.Marshal(b, m, deterministic)
}
func (m *UidMess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UidMess.Merge(m, src)
}
func (m *UidMess) XXX_Size() int {
	return xxx_messageInfo_UidMess.Size(m)
}
func (m *UidMess) XXX_DiscardUnknown() {
	xxx_messageInfo_UidMess.DiscardUnknown(m)
}

var xxx_messageInfo_UidMess proto.InternalMessageInfo

func (m *UidMess) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type SessionMess struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Expires              int64    `protobuf:"varint,3,opt,name=expires,proto3" json:"expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionMess) Reset()         { *m = SessionMess{} }
func (m *SessionMess) String() string { return proto.CompactTextString(m) }
func (*SessionMess) ProtoMessage()    {}
func (*SessionMess) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *SessionMess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionMess.Unmarshal(m, b)
}
func (m *SessionMess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionMess.Marshal(b, m, deterministic)
}
func (m *SessionMess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionMess.Merge(m, src)
}
func (m *SessionMess) XXX_Size() int {
	return xxx_messageInfo_SessionMess.Size(m)
}
func (m *SessionMess) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionMess.DiscardUnknown(m)
}

var xxx_messageInfo_SessionMess proto.InternalMessageInfo

func (m *SessionMess) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *SessionMess) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SessionMess) GetExpires() int64 {
	if m != nil {
		return m.Expires
	}
	return 0
}

type SidMess struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SidMess) Reset()         { *m = SidMess{} }
func (m *SidMess) String() string { return proto.CompactTextString(m) }
func (*SidMess) ProtoMessage()    {}
func (*SidMess) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *SidMess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SidMess.Unmarshal(m, b)
}
func (m *SidMess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SidMess.Marshal(b, m, deterministic)
}
func (m *SidMess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SidMess.Merge(m, src)
}
func (m *SidMess) XXX_Size() int {
	return xxx_messageInfo_SidMess.Size(m)
}
func (m *SidMess) XXX_DiscardUnknown() {
	xxx_messageInfo_SidMess.DiscardUnknown(m)
}

var xxx_messageInfo_SidMess proto.InternalMessageInfo

func (m *SidMess) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func init() {
	proto.RegisterType((*UserMess)(nil), "proto.UserMess")
	proto.RegisterType((*UidMess)(nil), "proto.UidMess")
	proto.RegisterType((*SessionMess)(nil), "proto.SessionMess")
	proto.RegisterType((*SidMess)(nil), "proto.SidMess")
}

func init() {
	proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd)
}

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x90, 0x4b, 0x4e, 0x80, 0x30,
	0x10, 0x86, 0xc3, 0x1b, 0xc6, 0x47, 0xcc, 0xc4, 0x98, 0x46, 0x37, 0x86, 0x95, 0x2b, 0x37, 0x1e,
	0xc3, 0xb8, 0x29, 0xe1, 0x00, 0x55, 0x1a, 0xd3, 0x28, 0x94, 0x74, 0x40, 0x3d, 0x95, 0x67, 0xb4,
	0x1d, 0x69, 0x8d, 0x2b, 0xfe, 0xff, 0xff, 0x3a, 0x2f, 0xe0, 0x6c, 0xd6, 0x44, 0xea, 0x55, 0xdf,
	0xaf, 0xce, 0x6e, 0x16, 0x2b, 0xfe, 0xf4, 0xdf, 0x19, 0xb4, 0x23, 0x69, 0xf7, 0xe4, 0x21, 0x9e,
	0x43, 0x6e, 0x26, 0x91, 0xdd, 0x66, 0x77, 0xa5, 0xf4, 0x0a, 0x11, 0xca, 0x45, 0xcd, 0x5a, 0xe4,
	0x3e, 0xe9, 0x24, 0x6b, 0x14, 0xd0, 0xd0, 0xee, 0x38, 0x2e, 0x38, 0x8e, 0x16, 0xaf, 0xa1, 0x5d,
	0xcc, 0xcb, 0x1b, 0xa3, 0x92, 0x51, 0xf2, 0x78, 0x09, 0x95, 0x9e, 0x95, 0x79, 0x17, 0x15, 0x83,
	0x5f, 0x83, 0x57, 0x50, 0xab, 0x0f, 0xb5, 0x29, 0x27, 0x6a, 0x8e, 0x0f, 0x17, 0x3a, 0xad, 0x8a,
	0xe8, 0xd3, 0xba, 0x49, 0x34, 0x9e, 0x9c, 0xca, 0xe4, 0xfb, 0x1b, 0x68, 0x46, 0x33, 0xf1, 0xba,
	0x17, 0x50, 0xec, 0x69, 0xdf, 0x20, 0xfb, 0x47, 0x38, 0x19, 0x3c, 0x31, 0x76, 0x89, 0x0f, 0xe8,
	0x78, 0xd0, 0xc9, 0x20, 0x63, 0x49, 0x9e, 0x4a, 0xc2, 0x3d, 0xfa, 0x6b, 0x35, 0x4e, 0x13, 0xdf,
	0x53, 0xc8, 0x68, 0xc3, 0xa4, 0xe1, 0x6f, 0xd2, 0xff, 0x46, 0xcf, 0x35, 0xff, 0xbe, 0x87, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x95, 0x07, 0x00, 0x56, 0x01, 0x00, 0x00,
}
