// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserMess struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Surname              string   `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
	Nickname             string   `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Avatar               string   `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Password             []byte   `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMess) Reset()         { *m = UserMess{} }
func (m *UserMess) String() string { return proto.CompactTextString(m) }
func (*UserMess) ProtoMessage()    {}
func (*UserMess) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *UserMess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMess.Unmarshal(m, b)
}
func (m *UserMess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMess.Marshal(b, m, deterministic)
}
func (m *UserMess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMess.Merge(m, src)
}
func (m *UserMess) XXX_Size() int {
	return xxx_messageInfo_UserMess.Size(m)
}
func (m *UserMess) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMess.DiscardUnknown(m)
}

var xxx_messageInfo_UserMess proto.InternalMessageInfo

func (m *UserMess) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserMess) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserMess) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *UserMess) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserMess) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserMess) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserMess) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

type UidMess struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UidMess) Reset()         { *m = UidMess{} }
func (m *UidMess) String() string { return proto.CompactTextString(m) }
func (*UidMess) ProtoMessage()    {}
func (*UidMess) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *UidMess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UidMess.Unmarshal(m, b)
}
func (m *UidMess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UidMess.Marshal(b, m, deterministic)
}
func (m *UidMess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UidMess.Merge(m, src)
}
func (m *UidMess) XXX_Size() int {
	return xxx_messageInfo_UidMess.Size(m)
}
func (m *UidMess) XXX_DiscardUnknown() {
	xxx_messageInfo_UidMess.DiscardUnknown(m)
}

var xxx_messageInfo_UidMess proto.InternalMessageInfo

func (m *UidMess) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type NicknameMess struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NicknameMess) Reset()         { *m = NicknameMess{} }
func (m *NicknameMess) String() string { return proto.CompactTextString(m) }
func (*NicknameMess) ProtoMessage()    {}
func (*NicknameMess) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *NicknameMess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NicknameMess.Unmarshal(m, b)
}
func (m *NicknameMess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NicknameMess.Marshal(b, m, deterministic)
}
func (m *NicknameMess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NicknameMess.Merge(m, src)
}
func (m *NicknameMess) XXX_Size() int {
	return xxx_messageInfo_NicknameMess.Size(m)
}
func (m *NicknameMess) XXX_DiscardUnknown() {
	xxx_messageInfo_NicknameMess.DiscardUnknown(m)
}

var xxx_messageInfo_NicknameMess proto.InternalMessageInfo

func (m *NicknameMess) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

type SessionMess struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Uid                  uint64   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Expires              int32    `protobuf:"varint,3,opt,name=expires,proto3" json:"expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionMess) Reset()         { *m = SessionMess{} }
func (m *SessionMess) String() string { return proto.CompactTextString(m) }
func (*SessionMess) ProtoMessage()    {}
func (*SessionMess) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *SessionMess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionMess.Unmarshal(m, b)
}
func (m *SessionMess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionMess.Marshal(b, m, deterministic)
}
func (m *SessionMess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionMess.Merge(m, src)
}
func (m *SessionMess) XXX_Size() int {
	return xxx_messageInfo_SessionMess.Size(m)
}
func (m *SessionMess) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionMess.DiscardUnknown(m)
}

var xxx_messageInfo_SessionMess proto.InternalMessageInfo

func (m *SessionMess) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *SessionMess) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SessionMess) GetExpires() int32 {
	if m != nil {
		return m.Expires
	}
	return 0
}

type SidMess struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SidMess) Reset()         { *m = SidMess{} }
func (m *SidMess) String() string { return proto.CompactTextString(m) }
func (*SidMess) ProtoMessage()    {}
func (*SidMess) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *SidMess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SidMess.Unmarshal(m, b)
}
func (m *SidMess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SidMess.Marshal(b, m, deterministic)
}
func (m *SidMess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SidMess.Merge(m, src)
}
func (m *SidMess) XXX_Size() int {
	return xxx_messageInfo_SidMess.Size(m)
}
func (m *SidMess) XXX_DiscardUnknown() {
	xxx_messageInfo_SidMess.DiscardUnknown(m)
}

var xxx_messageInfo_SidMess proto.InternalMessageInfo

func (m *SidMess) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type BoolMess struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolMess) Reset()         { *m = BoolMess{} }
func (m *BoolMess) String() string { return proto.CompactTextString(m) }
func (*BoolMess) ProtoMessage()    {}
func (*BoolMess) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *BoolMess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolMess.Unmarshal(m, b)
}
func (m *BoolMess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolMess.Marshal(b, m, deterministic)
}
func (m *BoolMess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolMess.Merge(m, src)
}
func (m *BoolMess) XXX_Size() int {
	return xxx_messageInfo_BoolMess.Size(m)
}
func (m *BoolMess) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolMess.DiscardUnknown(m)
}

var xxx_messageInfo_BoolMess proto.InternalMessageInfo

func (m *BoolMess) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type CheckPassMess struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Pass                 []byte   `protobuf:"bytes,2,opt,name=pass,proto3" json:"pass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPassMess) Reset()         { *m = CheckPassMess{} }
func (m *CheckPassMess) String() string { return proto.CompactTextString(m) }
func (*CheckPassMess) ProtoMessage()    {}
func (*CheckPassMess) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *CheckPassMess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPassMess.Unmarshal(m, b)
}
func (m *CheckPassMess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPassMess.Marshal(b, m, deterministic)
}
func (m *CheckPassMess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPassMess.Merge(m, src)
}
func (m *CheckPassMess) XXX_Size() int {
	return xxx_messageInfo_CheckPassMess.Size(m)
}
func (m *CheckPassMess) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPassMess.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPassMess proto.InternalMessageInfo

func (m *CheckPassMess) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CheckPassMess) GetPass() []byte {
	if m != nil {
		return m.Pass
	}
	return nil
}

type UpdateMess struct {
	OldPass              []byte    `protobuf:"bytes,1,opt,name=oldPass,proto3" json:"oldPass,omitempty"`
	Usr                  *UserMess `protobuf:"bytes,2,opt,name=usr,proto3" json:"usr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateMess) Reset()         { *m = UpdateMess{} }
func (m *UpdateMess) String() string { return proto.CompactTextString(m) }
func (*UpdateMess) ProtoMessage()    {}
func (*UpdateMess) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *UpdateMess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMess.Unmarshal(m, b)
}
func (m *UpdateMess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMess.Marshal(b, m, deterministic)
}
func (m *UpdateMess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMess.Merge(m, src)
}
func (m *UpdateMess) XXX_Size() int {
	return xxx_messageInfo_UpdateMess.Size(m)
}
func (m *UpdateMess) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMess.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMess proto.InternalMessageInfo

func (m *UpdateMess) GetOldPass() []byte {
	if m != nil {
		return m.OldPass
	}
	return nil
}

func (m *UpdateMess) GetUsr() *UserMess {
	if m != nil {
		return m.Usr
	}
	return nil
}

func init() {
	proto.RegisterType((*UserMess)(nil), "proto.UserMess")
	proto.RegisterType((*UidMess)(nil), "proto.UidMess")
	proto.RegisterType((*NicknameMess)(nil), "proto.NicknameMess")
	proto.RegisterType((*SessionMess)(nil), "proto.SessionMess")
	proto.RegisterType((*SidMess)(nil), "proto.SidMess")
	proto.RegisterType((*BoolMess)(nil), "proto.BoolMess")
	proto.RegisterType((*CheckPassMess)(nil), "proto.CheckPassMess")
	proto.RegisterType((*UpdateMess)(nil), "proto.UpdateMess")
}

func init() {
	proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd)
}

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x51, 0x4b, 0x4e, 0xc3, 0x30,
	0x14, 0x54, 0xda, 0xa6, 0x49, 0x5f, 0x53, 0x40, 0x16, 0x42, 0x16, 0x6c, 0xc0, 0x2b, 0xc4, 0xa2,
	0x0b, 0x10, 0x17, 0x80, 0x15, 0x42, 0x20, 0xe4, 0x2a, 0x07, 0x30, 0x8d, 0x05, 0x56, 0x3e, 0x8e,
	0xec, 0x14, 0x38, 0x15, 0x67, 0xc4, 0x7e, 0x89, 0x03, 0x95, 0x58, 0x65, 0xe6, 0x8d, 0x3d, 0x99,
	0xf1, 0x83, 0x55, 0x2d, 0xad, 0x15, 0x6f, 0x72, 0xdd, 0x1a, 0xdd, 0x69, 0x12, 0xe3, 0x87, 0x7d,
	0x47, 0x90, 0xe6, 0x56, 0x9a, 0x27, 0x27, 0x92, 0x03, 0x98, 0xa8, 0x82, 0x46, 0xe7, 0xd1, 0xe5,
	0x8c, 0x3b, 0x44, 0x08, 0xcc, 0x1a, 0x51, 0x4b, 0x3a, 0x71, 0x93, 0x05, 0x47, 0x4c, 0x28, 0x24,
	0x76, 0x67, 0x70, 0x3c, 0xc5, 0x71, 0xa0, 0xe4, 0x14, 0xd2, 0x46, 0x6d, 0x4b, 0x94, 0x66, 0x28,
	0x8d, 0x9c, 0x1c, 0x43, 0x2c, 0x6b, 0xa1, 0x2a, 0x1a, 0xa3, 0xd0, 0x13, 0x72, 0x02, 0x73, 0xf1,
	0x21, 0x3a, 0x61, 0xe8, 0x1c, 0xc7, 0x03, 0xf3, 0x4e, 0xad, 0xb0, 0xf6, 0x53, 0x9b, 0x82, 0x26,
	0x4e, 0xc9, 0xf8, 0xc8, 0xd9, 0x19, 0x24, 0xb9, 0x2a, 0x30, 0xee, 0x11, 0x4c, 0x77, 0x63, 0x5e,
	0x0f, 0xd9, 0x15, 0x64, 0xcf, 0xc3, 0x2f, 0xf1, 0xc4, 0xdf, 0x48, 0xd1, 0x7e, 0x24, 0xf6, 0x08,
	0xcb, 0x8d, 0x3b, 0xa3, 0x74, 0x13, 0xcc, 0xec, 0x60, 0xb6, 0xe0, 0x1e, 0x06, 0xfb, 0xc9, 0x68,
	0xef, 0xbb, 0xcb, 0xaf, 0x56, 0x19, 0x69, 0xb1, 0x7b, 0xcc, 0x03, 0xf5, 0xa9, 0x36, 0xbf, 0xa9,
	0xf6, 0x8d, 0x98, 0x4b, 0x71, 0xa7, 0x75, 0x15, 0x9e, 0x58, 0x97, 0x28, 0xa6, 0xdc, 0x21, 0x76,
	0x0b, 0xab, 0xfb, 0x77, 0xb9, 0x2d, 0x5f, 0x5c, 0xbf, 0xff, 0x4b, 0xf9, 0x2d, 0xf8, 0xf6, 0x18,
	0x24, 0xe3, 0x88, 0xd9, 0x03, 0x40, 0xde, 0x16, 0xa2, 0xeb, 0x6b, 0xba, 0x5c, 0xba, 0x2a, 0xbc,
	0x05, 0xde, 0xcb, 0x78, 0xa0, 0xe4, 0xc2, 0xb9, 0x59, 0x83, 0x57, 0x97, 0xd7, 0x87, 0xfd, 0xea,
	0xd7, 0x61, 0xdf, 0xdc, 0x6b, 0xaf, 0x73, 0x1c, 0xde, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0x06,
	0xc9, 0xb1, 0x83, 0x20, 0x02, 0x00, 0x00,
}
