{
 "title": "session service",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Count all requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(session_hits_total[5m])", "legendFormat": "count all requests" }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "статусы != 200",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(session_hits{status!=\"200\"}[5m])",
     "legendFormat": "{{status}} {{method}}"
    }
   ]
  },
  {
   "title": "Requests time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "timeticks" }
   ],
   "targets": [
    {
     "expr": "rate(session_times_sum[1m]) / rate(session_times_count[1m])",
     "legendFormat": "{{status}} {{method}}"
    }
   ]
  },
  {
   "title": "Quantile request time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "timeticks" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(session_times_bucket[5m])) by (le))",
     "legendFormat": "0.95 quantile req time"
    }
   ]
  },
  {
   "title": "Mallocs over last min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(go_memstats_mallocs_total{job=\"session\"}[1m])",
     "legendFormat": "mallocs"
    }
   ]
  },
  {
   "title": "Heap alloc bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"session\"}",
     "legendFormat": "heap alloc bytes"
    }
   ]
  }
 ]
}