// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "github.com/go-park-mail-ru/2020_1_SIBIRSKAYA_KORONA/app/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockRepository) Create(uid uint, board *models.Board) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", uid, board)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockRepositoryMockRecorder) Create(uid, board interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), uid, board)
}

// GetBoardsByUser mocks base method
func (m *MockRepository) GetBoardsByUser(uid uint) (models.Boards, models.Boards, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBoardsByUser", uid)
	ret0, _ := ret[0].(models.Boards)
	ret1, _ := ret[1].(models.Boards)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBoardsByUser indicates an expected call of GetBoardsByUser
func (mr *MockRepositoryMockRecorder) GetBoardsByUser(uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBoardsByUser", reflect.TypeOf((*MockRepository)(nil).GetBoardsByUser), uid)
}

// Get mocks base method
func (m *MockRepository) Get(bid uint) (*models.Board, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", bid)
	ret0, _ := ret[0].(*models.Board)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockRepositoryMockRecorder) Get(bid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), bid)
}

// GetLabelsByID mocks base method
func (m *MockRepository) GetLabelsByID(bid uint) (models.Labels, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLabelsByID", bid)
	ret0, _ := ret[0].(models.Labels)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLabelsByID indicates an expected call of GetLabelsByID
func (mr *MockRepositoryMockRecorder) GetLabelsByID(bid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLabelsByID", reflect.TypeOf((*MockRepository)(nil).GetLabelsByID), bid)
}

// GetColumnsByID mocks base method
func (m *MockRepository) GetColumnsByID(bid uint) (models.Columns, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetColumnsByID", bid)
	ret0, _ := ret[0].(models.Columns)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetColumnsByID indicates an expected call of GetColumnsByID
func (mr *MockRepositoryMockRecorder) GetColumnsByID(bid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetColumnsByID", reflect.TypeOf((*MockRepository)(nil).GetColumnsByID), bid)
}

// Update mocks base method
func (m *MockRepository) Update(board *models.Board) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", board)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockRepositoryMockRecorder) Update(board interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), board)
}

// Delete mocks base method
func (m *MockRepository) Delete(bid uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", bid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockRepositoryMockRecorder) Delete(bid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), bid)
}

// InviteMember mocks base method
func (m *MockRepository) InviteMember(bid uint, member *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InviteMember", bid, member)
	ret0, _ := ret[0].(error)
	return ret0
}

// InviteMember indicates an expected call of InviteMember
func (mr *MockRepositoryMockRecorder) InviteMember(bid, member interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InviteMember", reflect.TypeOf((*MockRepository)(nil).InviteMember), bid, member)
}

// DeleteMember mocks base method
func (m *MockRepository) DeleteMember(bid uint, member *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMember", bid, member)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMember indicates an expected call of DeleteMember
func (mr *MockRepositoryMockRecorder) DeleteMember(bid, member interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMember", reflect.TypeOf((*MockRepository)(nil).DeleteMember), bid, member)
}

// GetUsersForInvite mocks base method
func (m *MockRepository) GetUsersForInvite(bid uint, nicknamePart string, limit uint) (models.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersForInvite", bid, nicknamePart, limit)
	ret0, _ := ret[0].(models.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersForInvite indicates an expected call of GetUsersForInvite
func (mr *MockRepositoryMockRecorder) GetUsersForInvite(bid, nicknamePart, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersForInvite", reflect.TypeOf((*MockRepository)(nil).GetUsersForInvite), bid, nicknamePart, limit)
}

// InviteMemberByLink mocks base method
func (m *MockRepository) InviteMemberByLink(bid, uid uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InviteMemberByLink", bid, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// InviteMemberByLink indicates an expected call of InviteMemberByLink
func (mr *MockRepositoryMockRecorder) InviteMemberByLink(bid, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InviteMemberByLink", reflect.TypeOf((*MockRepository)(nil).InviteMemberByLink), bid, uid)
}

// UpdateInviteLink mocks base method
func (m *MockRepository) UpdateInviteLink(bid uint) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInviteLink", bid)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInviteLink indicates an expected call of UpdateInviteLink
func (mr *MockRepositoryMockRecorder) UpdateInviteLink(bid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInviteLink", reflect.TypeOf((*MockRepository)(nil).UpdateInviteLink), bid)
}
