# мемкэш и посгрес уже поднят
run-user-service:
	(go run user/main.go -c user/dev_config.yaml)&
run-session-service:
	(go run session/main.go -c session/dev_config.yaml)&
run-api-service:
	(go run api/main.go -c api/dev_config.yaml)&